apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo1-wind-turbine-app-dev
  annotations:
    argocd/app-name: demo1-wind-turbine-app-dev
    backstage.io/kubernetes-id: demo1-wind-turbine-app
    backstage.io/kubernetes-namespace: demo1
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: WindTurbineInc/demo1-wind-turbine
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.wearedevs.rl97.p1.openshiftapps.com/dev-pipelines/ns/demo1/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.wearedevs.rl97.p1.openshiftapps.com/k8s/ns/demo1/deployments/demo1-wind-turbine-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.wearedevs.rl97.p1.openshiftapps.com/#https://github.com/WindTurbineInc/demo1-wind-turbine?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/blues-man"
